/**
 * Tabla de armado de zonas y llave por cantidad de parejas (7 a 48).
 *
 * Copia fiel de APP_GRAL.llave y de los roundNcomplete del organizador
 * (src/constants.ts). Es una tabla hecha a mano: los tamanos chicos no siguen
 * un patron de siembra derivable y la ubicacion de los Bye esta elegida a
 * dedo, asi que se copia en lugar de generarse.
 *
 * Modulo puro (sin "use server"): lo importan las actions y los clients.
 */

/** Primera ronda de la llave: 4 = cuartos, 8 = octavos, 16 = dieciseisavos. */
export type LlaveRound = 4 | 8 | 16;

export type LlaveZonaTabla = {
  nombre: string;
  /** Numeros de siembra (1-based). El orden es la posicion en la zona: A1, A2, A3, A4. */
  parejas: number[];
};

export type LlaveEntry = {
  /** Cantidad total de parejas del torneo. */
  parejas: number;
  round: LlaveRound;
  /** Entrantes del cuadro en orden de slot: "1A" | "2B" | "3A" | "Bye". Se cruzan de a pares. */
  llave: string[];
  grupo: LlaveZonaTabla[];
  /** Partidos de zona: "A1-A4", "A2-A3", "AG1-AG2", "AP1-AP2", ... */
  partidos: string[];
};

export const LLAVE_TABLA: readonly LlaveEntry[] = [
  {
    parejas: 7,
    round: 4,
    llave: [
      "1A",
      "Bye",
      "3A",
      "2B",
      "2A",
      "Bye",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 4, 5, 7] },
      { nombre: "Zona B", parejas: [2, 3, 6] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B2",
      "B1-B3",
      "B2-B3",
    ],
  },
  {
    parejas: 8,
    round: 4,
    llave: [
      "1A",
      "Bye",
      "3A",
      "2B",
      "2A",
      "3B",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 4, 5, 7] },
      { nombre: "Zona B", parejas: [2, 3, 6, 8] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B4",
      "B2-B3",
      "BG1-BG2",
      "BP1-BP2",
    ],
  },
  {
    parejas: 9,
    round: 4,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2C",
      "1C",
      "2A",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 6, 7] },
      { nombre: "Zona B", parejas: [2, 5, 8] },
      { nombre: "Zona C", parejas: [3, 4, 9] },
    ],
    partidos: [
      "A1-A2",
      "A2-A3",
      "A1-A3",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
    ],
  },
  {
    parejas: 10,
    round: 4,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2C",
      "1C",
      "2A",
      "3A",
      "1B",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 6, 7, 10] },
      { nombre: "Zona B", parejas: [2, 5, 8] },
      { nombre: "Zona C", parejas: [3, 4, 9] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
    ],
  },
  {
    parejas: 11,
    round: 4,
    llave: [
      "1A",
      "3B",
      "2B",
      "2C",
      "1C",
      "2A",
      "3A",
      "1B",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 6, 7, 10] },
      { nombre: "Zona B", parejas: [2, 5, 8, 11] },
      { nombre: "Zona C", parejas: [3, 4, 9] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B4",
      "B2-B3",
      "BG1-BG2",
      "BP1-BP2",
      "C1-C2",
      "C2-C3",
      "C1-C3",
    ],
  },
  {
    parejas: 12,
    round: 4,
    llave: [
      "1A",
      "2B",
      "2C",
      "1D",
      "1C",
      "2D",
      "2A",
      "1B",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 8, 9] },
      { nombre: "Zona B", parejas: [2, 7, 10] },
      { nombre: "Zona C", parejas: [3, 6, 11] },
      { nombre: "Zona D", parejas: [4, 5, 12] },
    ],
    partidos: [
      "A1-A2",
      "A2-A3",
      "A1-A3",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
    ],
  },
  {
    parejas: 13,
    round: 8,
    llave: [
      "1A",
      "Bye",
      "3A",
      "2B",
      "2C",
      "Bye",
      "1D",
      "Bye",
      "1C",
      "Bye",
      "2D",
      "Bye",
      "2A",
      "Bye",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 8, 9, 13] },
      { nombre: "Zona B", parejas: [2, 7, 10] },
      { nombre: "Zona C", parejas: [3, 6, 11] },
      { nombre: "Zona D", parejas: [4, 5, 12] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
    ],
  },
  {
    parejas: 14,
    round: 8,
    llave: [
      "1A",
      "Bye",
      "3A",
      "2B",
      "2C",
      "Bye",
      "1D",
      "Bye",
      "1C",
      "Bye",
      "2D",
      "Bye",
      "2A",
      "3B",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 8, 9, 13] },
      { nombre: "Zona B", parejas: [2, 7, 10, 14] },
      { nombre: "Zona C", parejas: [3, 6, 11] },
      { nombre: "Zona D", parejas: [4, 5, 12] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B4",
      "B2-B3",
      "BG1-BG2",
      "BP1-BP2",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
    ],
  },
  {
    parejas: 15,
    round: 8,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2C",
      "1E",
      "Bye",
      "1D",
      "Bye",
      "1C",
      "Bye",
      "2E",
      "Bye",
      "2D",
      "2A",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 10, 11] },
      { nombre: "Zona B", parejas: [2, 9, 12] },
      { nombre: "Zona C", parejas: [3, 8, 13] },
      { nombre: "Zona D", parejas: [4, 7, 14] },
      { nombre: "Zona E", parejas: [5, 6, 15] },
    ],
    partidos: [
      "A1-A3",
      "A2-A3",
      "A1-A2",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
    ],
  },
  {
    parejas: 16,
    round: 8,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2C",
      "1E",
      "Bye",
      "1D",
      "Bye",
      "1C",
      "Bye",
      "3A",
      "2E",
      "2D",
      "2A",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 10, 11, 16] },
      { nombre: "Zona B", parejas: [2, 9, 12] },
      { nombre: "Zona C", parejas: [3, 8, 13] },
      { nombre: "Zona D", parejas: [4, 7, 14] },
      { nombre: "Zona E", parejas: [5, 6, 15] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
    ],
  },
  {
    parejas: 17,
    round: 8,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2C",
      "1E",
      "3B",
      "1D",
      "Bye",
      "1C",
      "Bye",
      "3A",
      "2E",
      "2D",
      "2A",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 10, 11, 16] },
      { nombre: "Zona B", parejas: [2, 9, 12, 17] },
      { nombre: "Zona C", parejas: [3, 8, 13] },
      { nombre: "Zona D", parejas: [4, 7, 14] },
      { nombre: "Zona E", parejas: [5, 6, 15] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B4",
      "B2-B3",
      "BG1-BG2",
      "BP1-BP2",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
    ],
  },
  {
    parejas: 18,
    round: 8,
    llave: [
      "1A",
      "Bye",
      "2C",
      "2F",
      "1E",
      "2B",
      "1D",
      "Bye",
      "1C",
      "Bye",
      "2A",
      "1F",
      "2E",
      "2D",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 12, 13] },
      { nombre: "Zona B", parejas: [2, 11, 14] },
      { nombre: "Zona C", parejas: [3, 10, 15] },
      { nombre: "Zona D", parejas: [4, 9, 16] },
      { nombre: "Zona E", parejas: [5, 8, 17] },
      { nombre: "Zona F", parejas: [6, 7, 18] },
    ],
    partidos: [
      "A1-A3",
      "A2-A3",
      "A1-A2",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
    ],
  },
  {
    parejas: 19,
    round: 8,
    llave: [
      "1A",
      "Bye",
      "2C",
      "2F",
      "1E",
      "2B",
      "3A",
      "1D",
      "1C",
      "Bye",
      "2A",
      "1F",
      "2E",
      "2D",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 12, 13, 19] },
      { nombre: "Zona B", parejas: [2, 11, 14] },
      { nombre: "Zona C", parejas: [3, 10, 15] },
      { nombre: "Zona D", parejas: [4, 9, 16] },
      { nombre: "Zona E", parejas: [5, 8, 17] },
      { nombre: "Zona F", parejas: [6, 7, 18] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
    ],
  },
  {
    parejas: 20,
    round: 8,
    llave: [
      "1A",
      "Bye",
      "2C",
      "2F",
      "1E",
      "2B",
      "3A",
      "1D",
      "1C",
      "3B",
      "2A",
      "1F",
      "2E",
      "2D",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 12, 13, 19] },
      { nombre: "Zona B", parejas: [2, 11, 14, 20] },
      { nombre: "Zona C", parejas: [3, 10, 15] },
      { nombre: "Zona D", parejas: [4, 9, 16] },
      { nombre: "Zona E", parejas: [5, 8, 17] },
      { nombre: "Zona F", parejas: [6, 7, 18] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B4",
      "B2-B3",
      "BG1-BG2",
      "BP1-BP2",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
    ],
  },
  {
    parejas: 21,
    round: 8,
    llave: [
      "1A",
      "Bye",
      "2F",
      "2G",
      "1E",
      "2C",
      "2B",
      "1D",
      "1C",
      "2A",
      "2D",
      "1F",
      "1G",
      "2E",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 14, 15] },
      { nombre: "Zona B", parejas: [2, 13, 16] },
      { nombre: "Zona C", parejas: [3, 12, 17] },
      { nombre: "Zona D", parejas: [4, 11, 18] },
      { nombre: "Zona E", parejas: [5, 10, 19] },
      { nombre: "Zona F", parejas: [6, 9, 20] },
      { nombre: "Zona G", parejas: [7, 8, 21] },
    ],
    partidos: [
      "A1-A2",
      "A2-A3",
      "A1-A3",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
    ],
  },
  {
    parejas: 22,
    round: 8,
    llave: [
      "1A",
      "Bye",
      "2F",
      "2G",
      "1E",
      "2C",
      "2B",
      "1D",
      "1C",
      "2A",
      "2D",
      "1F",
      "1G",
      "2E",
      "3A",
      "1B",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 14, 15, 22] },
      { nombre: "Zona B", parejas: [2, 13, 16] },
      { nombre: "Zona C", parejas: [3, 12, 17] },
      { nombre: "Zona D", parejas: [4, 11, 18] },
      { nombre: "Zona E", parejas: [5, 10, 19] },
      { nombre: "Zona F", parejas: [6, 9, 20] },
      { nombre: "Zona G", parejas: [7, 8, 21] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
    ],
  },
  {
    parejas: 23,
    round: 8,
    llave: [
      "1A",
      "3B",
      "2F",
      "2G",
      "1E",
      "2C",
      "2B",
      "1D",
      "1C",
      "2A",
      "2D",
      "1F",
      "1G",
      "2E",
      "3A",
      "1B",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 14, 15, 22] },
      { nombre: "Zona B", parejas: [2, 13, 16, 23] },
      { nombre: "Zona C", parejas: [3, 12, 17] },
      { nombre: "Zona D", parejas: [4, 11, 18] },
      { nombre: "Zona E", parejas: [5, 10, 19] },
      { nombre: "Zona F", parejas: [6, 9, 20] },
      { nombre: "Zona G", parejas: [7, 8, 21] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B4",
      "B2-B3",
      "BG1-BG2",
      "BP1-BP2",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
    ],
  },
  {
    parejas: 24,
    round: 8,
    llave: [
      "1A",
      "2B",
      "2G",
      "1H",
      "1E",
      "2F",
      "2C",
      "1D",
      "1C",
      "2D",
      "2E",
      "1F",
      "1G",
      "2H",
      "2A",
      "1B",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 16, 17] },
      { nombre: "Zona B", parejas: [2, 15, 18] },
      { nombre: "Zona C", parejas: [3, 14, 19] },
      { nombre: "Zona D", parejas: [4, 13, 20] },
      { nombre: "Zona E", parejas: [5, 12, 21] },
      { nombre: "Zona F", parejas: [6, 11, 22] },
      { nombre: "Zona G", parejas: [7, 10, 23] },
      { nombre: "Zona H", parejas: [8, 9, 24] },
    ],
    partidos: [
      "A1-A2",
      "A2-A3",
      "A1-A3",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
    ],
  },
  {
    parejas: 25,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "3A",
      "2B",
      "2G",
      "Bye",
      "1H",
      "Bye",
      "1E",
      "Bye",
      "2F",
      "Bye",
      "2C",
      "Bye",
      "1D",
      "Bye",
      "1C",
      "Bye",
      "2D",
      "Bye",
      "2E",
      "Bye",
      "1F",
      "Bye",
      "1G",
      "Bye",
      "2H",
      "Bye",
      "2A",
      "Bye",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 16, 17, 25] },
      { nombre: "Zona B", parejas: [2, 15, 18] },
      { nombre: "Zona C", parejas: [3, 14, 19] },
      { nombre: "Zona D", parejas: [4, 13, 20] },
      { nombre: "Zona E", parejas: [5, 12, 21] },
      { nombre: "Zona F", parejas: [6, 11, 22] },
      { nombre: "Zona G", parejas: [7, 10, 23] },
      { nombre: "Zona H", parejas: [8, 9, 24] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
    ],
  },
  {
    parejas: 26,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "3A",
      "2B",
      "2G",
      "Bye",
      "1H",
      "Bye",
      "1E",
      "Bye",
      "2F",
      "Bye",
      "2C",
      "Bye",
      "1D",
      "Bye",
      "1C",
      "Bye",
      "2D",
      "Bye",
      "2E",
      "Bye",
      "1F",
      "Bye",
      "1G",
      "Bye",
      "2H",
      "Bye",
      "2A",
      "3B",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 16, 17, 25] },
      { nombre: "Zona B", parejas: [2, 15, 18, 26] },
      { nombre: "Zona C", parejas: [3, 14, 19] },
      { nombre: "Zona D", parejas: [4, 13, 20] },
      { nombre: "Zona E", parejas: [5, 12, 21] },
      { nombre: "Zona F", parejas: [6, 11, 22] },
      { nombre: "Zona G", parejas: [7, 10, 23] },
      { nombre: "Zona H", parejas: [8, 9, 24] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B4",
      "B2-B3",
      "BG1-BG2",
      "BP1-BP2",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
    ],
  },
  {
    parejas: 27,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "2B",
      "Bye",
      "2F",
      "2I",
      "1E",
      "Bye",
      "1G",
      "Bye",
      "2D",
      "Bye",
      "2H",
      "Bye",
      "1C",
      "Bye",
      "1D",
      "Bye",
      "2C",
      "Bye",
      "2G",
      "Bye",
      "1F",
      "Bye",
      "1H",
      "Bye",
      "1I",
      "Bye",
      "2A",
      "2E",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 18, 19] },
      { nombre: "Zona B", parejas: [2, 17, 20] },
      { nombre: "Zona C", parejas: [3, 16, 21] },
      { nombre: "Zona D", parejas: [4, 15, 22] },
      { nombre: "Zona E", parejas: [5, 14, 23] },
      { nombre: "Zona F", parejas: [6, 13, 24] },
      { nombre: "Zona G", parejas: [7, 12, 25] },
      { nombre: "Zona H", parejas: [8, 11, 26] },
      { nombre: "Zona I", parejas: [9, 10, 27] },
    ],
    partidos: [
      "A1-A2",
      "A2-A3",
      "A1-A3",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
    ],
  },
  {
    parejas: 28,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "2B",
      "Bye",
      "2I",
      "2F",
      "1E",
      "Bye",
      "1G",
      "Bye",
      "2H",
      "3A",
      "2D",
      "Bye",
      "1C",
      "Bye",
      "1D",
      "Bye",
      "2C",
      "Bye",
      "2G",
      "Bye",
      "1F",
      "Bye",
      "1H",
      "Bye",
      "1I",
      "Bye",
      "2A",
      "2E",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 18, 19, 28] },
      { nombre: "Zona B", parejas: [2, 17, 20] },
      { nombre: "Zona C", parejas: [3, 16, 21] },
      { nombre: "Zona D", parejas: [4, 15, 22] },
      { nombre: "Zona E", parejas: [5, 14, 23] },
      { nombre: "Zona F", parejas: [6, 13, 24] },
      { nombre: "Zona G", parejas: [7, 12, 25] },
      { nombre: "Zona H", parejas: [8, 11, 26] },
      { nombre: "Zona I", parejas: [9, 10, 27] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
    ],
  },
  {
    parejas: 29,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "2B",
      "Bye",
      "2I",
      "2F",
      "1E",
      "Bye",
      "1G",
      "Bye",
      "2H",
      "3A",
      "2D",
      "Bye",
      "1C",
      "Bye",
      "1D",
      "Bye",
      "2C",
      "Bye",
      "2G",
      "3B",
      "1F",
      "Bye",
      "1H",
      "Bye",
      "1I",
      "Bye",
      "2A",
      "2E",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 18, 19, 28] },
      { nombre: "Zona B", parejas: [2, 17, 20, 29] },
      { nombre: "Zona C", parejas: [3, 16, 21] },
      { nombre: "Zona D", parejas: [4, 15, 22] },
      { nombre: "Zona E", parejas: [5, 14, 23] },
      { nombre: "Zona F", parejas: [6, 13, 24] },
      { nombre: "Zona G", parejas: [7, 12, 25] },
      { nombre: "Zona H", parejas: [8, 11, 26] },
      { nombre: "Zona I", parejas: [9, 10, 27] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B4",
      "B2-B3",
      "BG1-BG2",
      "BP1-BP2",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
    ],
  },
  {
    parejas: 30,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2F",
      "1I",
      "Bye",
      "1E",
      "Bye",
      "1G",
      "Bye",
      "2H",
      "2J",
      "2D",
      "Bye",
      "1C",
      "Bye",
      "1D",
      "Bye",
      "2C",
      "Bye",
      "2G",
      "2I",
      "1F",
      "Bye",
      "1H",
      "Bye",
      "1J",
      "Bye",
      "2A",
      "2E",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 20, 21] },
      { nombre: "Zona B", parejas: [2, 19, 22] },
      { nombre: "Zona C", parejas: [3, 18, 23] },
      { nombre: "Zona D", parejas: [4, 17, 24] },
      { nombre: "Zona E", parejas: [5, 16, 25] },
      { nombre: "Zona F", parejas: [6, 15, 26] },
      { nombre: "Zona G", parejas: [7, 14, 27] },
      { nombre: "Zona H", parejas: [8, 13, 28] },
      { nombre: "Zona I", parejas: [9, 12, 29] },
      { nombre: "Zona J", parejas: [10, 11, 30] },
    ],
    partidos: [
      "A1-A2",
      "A2-A3",
      "A1-A3",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
      "J1-J2",
      "J2-J3",
      "J1-J3",
    ],
  },
  {
    parejas: 31,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2F",
      "1I",
      "Bye",
      "1E",
      "Bye",
      "1G",
      "Bye",
      "2H",
      "2J",
      "2D",
      "3A",
      "1C",
      "Bye",
      "1D",
      "Bye",
      "2C",
      "Bye",
      "2G",
      "2I",
      "1F",
      "Bye",
      "1H",
      "Bye",
      "1J",
      "Bye",
      "2A",
      "2E",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 20, 21, 31] },
      { nombre: "Zona B", parejas: [2, 19, 22] },
      { nombre: "Zona C", parejas: [3, 18, 23] },
      { nombre: "Zona D", parejas: [4, 17, 24] },
      { nombre: "Zona E", parejas: [5, 16, 25] },
      { nombre: "Zona F", parejas: [6, 15, 26] },
      { nombre: "Zona G", parejas: [7, 14, 27] },
      { nombre: "Zona H", parejas: [8, 13, 28] },
      { nombre: "Zona I", parejas: [9, 12, 29] },
      { nombre: "Zona J", parejas: [10, 11, 30] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
      "J1-J2",
      "J2-J3",
      "J1-J3",
    ],
  },
  {
    parejas: 32,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2F",
      "1I",
      "Bye",
      "1E",
      "Bye",
      "1G",
      "Bye",
      "2H",
      "2J",
      "2D",
      "3A",
      "1C",
      "Bye",
      "1D",
      "Bye",
      "2C",
      "3B",
      "2G",
      "2I",
      "1F",
      "Bye",
      "1H",
      "Bye",
      "1J",
      "Bye",
      "2A",
      "2E",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 20, 21, 31] },
      { nombre: "Zona B", parejas: [2, 19, 22, 32] },
      { nombre: "Zona C", parejas: [3, 18, 23] },
      { nombre: "Zona D", parejas: [4, 17, 24] },
      { nombre: "Zona E", parejas: [5, 16, 25] },
      { nombre: "Zona F", parejas: [6, 15, 26] },
      { nombre: "Zona G", parejas: [7, 14, 27] },
      { nombre: "Zona H", parejas: [8, 13, 28] },
      { nombre: "Zona I", parejas: [9, 12, 29] },
      { nombre: "Zona J", parejas: [10, 11, 30] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B4",
      "B2-B3",
      "BG1-BG2",
      "BP1-BP2",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
      "J1-J2",
      "J2-J3",
      "J1-J3",
    ],
  },
  {
    parejas: 33,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2F",
      "1I",
      "Bye",
      "1E",
      "Bye",
      "1G",
      "Bye",
      "1K",
      "2J",
      "2D",
      "2H",
      "1C",
      "Bye",
      "1D",
      "Bye",
      "2C",
      "2K",
      "2G",
      "2I",
      "1F",
      "Bye",
      "1H",
      "Bye",
      "1J",
      "Bye",
      "2A",
      "2E",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 22, 23] },
      { nombre: "Zona B", parejas: [2, 21, 24] },
      { nombre: "Zona C", parejas: [3, 20, 25] },
      { nombre: "Zona D", parejas: [4, 19, 26] },
      { nombre: "Zona E", parejas: [5, 18, 27] },
      { nombre: "Zona F", parejas: [6, 17, 28] },
      { nombre: "Zona G", parejas: [7, 16, 29] },
      { nombre: "Zona H", parejas: [8, 15, 30] },
      { nombre: "Zona I", parejas: [9, 14, 31] },
      { nombre: "Zona J", parejas: [10, 13, 32] },
      { nombre: "Zona K", parejas: [11, 12, 33] },
    ],
    partidos: [
      "A1-A2",
      "A2-A3",
      "A1-A3",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
      "J1-J2",
      "J2-J3",
      "J1-J3",
      "K1-K2",
      "K2-K3",
      "K1-K3",
    ],
  },
  {
    parejas: 34,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2F",
      "1I",
      "Bye",
      "1E",
      "Bye",
      "1G",
      "Bye",
      "1K",
      "2J",
      "2D",
      "2H",
      "1C",
      "Bye",
      "1D",
      "Bye",
      "2C",
      "2K",
      "2G",
      "2I",
      "1F",
      "Bye",
      "1H",
      "Bye",
      "1J",
      "3A",
      "2A",
      "2E",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 22, 23, 34] },
      { nombre: "Zona B", parejas: [2, 21, 24] },
      { nombre: "Zona C", parejas: [3, 20, 25] },
      { nombre: "Zona D", parejas: [4, 19, 26] },
      { nombre: "Zona E", parejas: [5, 18, 27] },
      { nombre: "Zona F", parejas: [6, 17, 28] },
      { nombre: "Zona G", parejas: [7, 16, 29] },
      { nombre: "Zona H", parejas: [8, 15, 30] },
      { nombre: "Zona I", parejas: [9, 14, 31] },
      { nombre: "Zona J", parejas: [10, 13, 32] },
      { nombre: "Zona K", parejas: [11, 12, 33] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
      "J1-J2",
      "J2-J3",
      "J1-J3",
      "K1-K2",
      "K2-K3",
      "K1-K3",
    ],
  },
  {
    parejas: 35,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2F",
      "1I",
      "3B",
      "1E",
      "Bye",
      "1G",
      "Bye",
      "1K",
      "2J",
      "2D",
      "2H",
      "1C",
      "Bye",
      "1D",
      "Bye",
      "2C",
      "2K",
      "2G",
      "2I",
      "1F",
      "Bye",
      "1H",
      "Bye",
      "1J",
      "3A",
      "2A",
      "2E",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 22, 23, 34] },
      { nombre: "Zona B", parejas: [2, 21, 24, 35] },
      { nombre: "Zona C", parejas: [3, 20, 25] },
      { nombre: "Zona D", parejas: [4, 19, 26] },
      { nombre: "Zona E", parejas: [5, 18, 27] },
      { nombre: "Zona F", parejas: [6, 17, 28] },
      { nombre: "Zona G", parejas: [7, 16, 29] },
      { nombre: "Zona H", parejas: [8, 15, 30] },
      { nombre: "Zona I", parejas: [9, 14, 31] },
      { nombre: "Zona J", parejas: [10, 13, 32] },
      { nombre: "Zona K", parejas: [11, 12, 33] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B4",
      "B2-B3",
      "BG1-BG2",
      "BP1-BP2",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
      "J1-J2",
      "J2-J3",
      "J1-J3",
      "K1-K2",
      "K2-K3",
      "K1-K3",
    ],
  },
  {
    parejas: 36,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2F",
      "1I",
      "2J",
      "1E",
      "Bye",
      "1G",
      "Bye",
      "1K",
      "2L",
      "2D",
      "2H",
      "1C",
      "Bye",
      "1D",
      "Bye",
      "2C",
      "2G",
      "1L",
      "2I",
      "1F",
      "Bye",
      "1H",
      "Bye",
      "1J",
      "2K",
      "2A",
      "2E",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 24, 25] },
      { nombre: "Zona B", parejas: [2, 23, 26] },
      { nombre: "Zona C", parejas: [3, 22, 27] },
      { nombre: "Zona D", parejas: [4, 21, 28] },
      { nombre: "Zona E", parejas: [5, 20, 29] },
      { nombre: "Zona F", parejas: [6, 19, 30] },
      { nombre: "Zona G", parejas: [7, 18, 31] },
      { nombre: "Zona H", parejas: [8, 17, 32] },
      { nombre: "Zona I", parejas: [9, 16, 33] },
      { nombre: "Zona J", parejas: [10, 15, 34] },
      { nombre: "Zona K", parejas: [11, 14, 35] },
      { nombre: "Zona L", parejas: [12, 13, 36] },
    ],
    partidos: [
      "A1-A2",
      "A2-A3",
      "A1-A3",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
      "J1-J2",
      "J2-J3",
      "J1-J3",
      "K1-K2",
      "K2-K3",
      "K1-K3",
      "L1-L2",
      "L2-L3",
      "L1-L3",
    ],
  },
  {
    parejas: 37,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2F",
      "1I",
      "2J",
      "1E",
      "Bye",
      "1G",
      "Bye",
      "1K",
      "2L",
      "2D",
      "2H",
      "1C",
      "Bye",
      "1D",
      "Bye",
      "2C",
      "2G",
      "1L",
      "2I",
      "1F",
      "Bye",
      "1H",
      "3A",
      "1J",
      "2K",
      "2A",
      "2E",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 24, 25, 37] },
      { nombre: "Zona B", parejas: [2, 23, 26] },
      { nombre: "Zona C", parejas: [3, 22, 27] },
      { nombre: "Zona D", parejas: [4, 21, 28] },
      { nombre: "Zona E", parejas: [5, 20, 29] },
      { nombre: "Zona F", parejas: [6, 19, 30] },
      { nombre: "Zona G", parejas: [7, 18, 31] },
      { nombre: "Zona H", parejas: [8, 17, 32] },
      { nombre: "Zona I", parejas: [9, 16, 33] },
      { nombre: "Zona J", parejas: [10, 15, 34] },
      { nombre: "Zona K", parejas: [11, 14, 35] },
      { nombre: "Zona L", parejas: [12, 13, 36] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
      "J1-J2",
      "J2-J3",
      "J1-J3",
      "K1-K2",
      "K2-K3",
      "K1-K3",
      "L1-L2",
      "L2-L3",
      "L1-L3",
    ],
  },
  {
    parejas: 38,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2F",
      "1I",
      "2J",
      "1E",
      "Bye",
      "1G",
      "3B",
      "1K",
      "2L",
      "2D",
      "2H",
      "1C",
      "Bye",
      "1D",
      "Bye",
      "2C",
      "2G",
      "1L",
      "2I",
      "1F",
      "Bye",
      "1H",
      "3A",
      "1J",
      "2K",
      "2A",
      "2E",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 24, 25, 37] },
      { nombre: "Zona B", parejas: [2, 23, 26, 38] },
      { nombre: "Zona C", parejas: [3, 22, 27] },
      { nombre: "Zona D", parejas: [4, 21, 28] },
      { nombre: "Zona E", parejas: [5, 20, 29] },
      { nombre: "Zona F", parejas: [6, 19, 30] },
      { nombre: "Zona G", parejas: [7, 18, 31] },
      { nombre: "Zona H", parejas: [8, 17, 32] },
      { nombre: "Zona I", parejas: [9, 16, 33] },
      { nombre: "Zona J", parejas: [10, 15, 34] },
      { nombre: "Zona K", parejas: [11, 14, 35] },
      { nombre: "Zona L", parejas: [12, 13, 36] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B4",
      "B2-B3",
      "BG1-BG2",
      "BP1-BP2",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
      "J1-J2",
      "J2-J3",
      "J1-J3",
      "K1-K2",
      "K2-K3",
      "K1-K3",
      "L1-L2",
      "L2-L3",
      "L1-L3",
    ],
  },
  {
    parejas: 39,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2F",
      "1I",
      "2J",
      "1E",
      "Bye",
      "1G",
      "2L",
      "1K",
      "2H",
      "1M",
      "2D",
      "1C",
      "Bye",
      "1D",
      "Bye",
      "2C",
      "2G",
      "1L",
      "2I",
      "1F",
      "Bye",
      "1H",
      "2M",
      "1J",
      "2K",
      "2A",
      "2E",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 26, 27] },
      { nombre: "Zona B", parejas: [2, 25, 28] },
      { nombre: "Zona C", parejas: [3, 24, 29] },
      { nombre: "Zona D", parejas: [4, 23, 30] },
      { nombre: "Zona E", parejas: [5, 22, 31] },
      { nombre: "Zona F", parejas: [6, 21, 32] },
      { nombre: "Zona G", parejas: [7, 20, 33] },
      { nombre: "Zona H", parejas: [8, 19, 34] },
      { nombre: "Zona I", parejas: [9, 18, 35] },
      { nombre: "Zona J", parejas: [10, 17, 36] },
      { nombre: "Zona K", parejas: [11, 16, 37] },
      { nombre: "Zona L", parejas: [12, 15, 38] },
      { nombre: "Zona M", parejas: [13, 14, 39] },
    ],
    partidos: [
      "A1-A2",
      "A2-A3",
      "A1-A3",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
      "J1-J2",
      "J2-J3",
      "J1-J3",
      "K1-K2",
      "K2-K3",
      "K1-K3",
      "L1-L2",
      "L2-L3",
      "L1-L3",
      "M1-M2",
      "M2-M3",
      "M1-M3",
    ],
  },
  {
    parejas: 40,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2F",
      "1I",
      "2J",
      "1E",
      "Bye",
      "1G",
      "2L",
      "1K",
      "2H",
      "1M",
      "2D",
      "1C",
      "Bye",
      "1D",
      "Bye",
      "2C",
      "2G",
      "1L",
      "2I",
      "1F",
      "3A",
      "1H",
      "2M",
      "1J",
      "2K",
      "2A",
      "2E",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 26, 27, 40] },
      { nombre: "Zona B", parejas: [2, 25, 28] },
      { nombre: "Zona C", parejas: [3, 24, 29] },
      { nombre: "Zona D", parejas: [4, 23, 30] },
      { nombre: "Zona E", parejas: [5, 22, 31] },
      { nombre: "Zona F", parejas: [6, 21, 32] },
      { nombre: "Zona G", parejas: [7, 20, 33] },
      { nombre: "Zona H", parejas: [8, 19, 34] },
      { nombre: "Zona I", parejas: [9, 18, 35] },
      { nombre: "Zona J", parejas: [10, 17, 36] },
      { nombre: "Zona K", parejas: [11, 16, 37] },
      { nombre: "Zona L", parejas: [12, 15, 38] },
      { nombre: "Zona M", parejas: [13, 14, 39] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
      "J1-J2",
      "J2-J3",
      "J1-J3",
      "K1-K2",
      "K2-K3",
      "K1-K3",
      "L1-L2",
      "L2-L3",
      "L1-L3",
      "M1-M2",
      "M2-M3",
      "M1-M3",
    ],
  },
  {
    parejas: 41,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2F",
      "1I",
      "2J",
      "1E",
      "3B",
      "1G",
      "2L",
      "1K",
      "2H",
      "1M",
      "2D",
      "1C",
      "Bye",
      "1D",
      "Bye",
      "2C",
      "2G",
      "1L",
      "2I",
      "1F",
      "3A",
      "1H",
      "2M",
      "1J",
      "2K",
      "2A",
      "2E",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 26, 27, 40] },
      { nombre: "Zona B", parejas: [2, 25, 28, 41] },
      { nombre: "Zona C", parejas: [3, 24, 29] },
      { nombre: "Zona D", parejas: [4, 23, 30] },
      { nombre: "Zona E", parejas: [5, 22, 31] },
      { nombre: "Zona F", parejas: [6, 21, 32] },
      { nombre: "Zona G", parejas: [7, 20, 33] },
      { nombre: "Zona H", parejas: [8, 19, 34] },
      { nombre: "Zona I", parejas: [9, 18, 35] },
      { nombre: "Zona J", parejas: [10, 17, 36] },
      { nombre: "Zona K", parejas: [11, 16, 37] },
      { nombre: "Zona L", parejas: [12, 15, 38] },
      { nombre: "Zona M", parejas: [13, 14, 39] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B4",
      "B2-B3",
      "BG1-BG2",
      "BP1-BP2",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
      "J1-J2",
      "J2-J3",
      "J1-J3",
      "K1-K2",
      "K2-K3",
      "K1-K3",
      "L1-L2",
      "L2-L3",
      "L1-L3",
      "M1-M2",
      "M2-M3",
      "M1-M3",
    ],
  },
  {
    parejas: 42,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2F",
      "1I",
      "2J",
      "1E",
      "2N",
      "1G",
      "2L",
      "1K",
      "2H",
      "1M",
      "2D",
      "1C",
      "Bye",
      "1D",
      "Bye",
      "1N",
      "2C",
      "1L",
      "2G",
      "1F",
      "2I",
      "1H",
      "2M",
      "1J",
      "2K",
      "2A",
      "2E",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 28, 29] },
      { nombre: "Zona B", parejas: [2, 27, 30] },
      { nombre: "Zona C", parejas: [3, 26, 31] },
      { nombre: "Zona D", parejas: [4, 25, 32] },
      { nombre: "Zona E", parejas: [5, 24, 33] },
      { nombre: "Zona F", parejas: [6, 23, 34] },
      { nombre: "Zona G", parejas: [7, 22, 35] },
      { nombre: "Zona H", parejas: [8, 21, 36] },
      { nombre: "Zona I", parejas: [9, 20, 37] },
      { nombre: "Zona J", parejas: [10, 19, 38] },
      { nombre: "Zona K", parejas: [11, 18, 39] },
      { nombre: "Zona L", parejas: [12, 17, 40] },
      { nombre: "Zona M", parejas: [13, 16, 41] },
      { nombre: "Zona N", parejas: [14, 15, 42] },
    ],
    partidos: [
      "A1-A2",
      "A2-A3",
      "A1-A3",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
      "J1-J2",
      "J2-J3",
      "J1-J3",
      "K1-K2",
      "K2-K3",
      "K1-K3",
      "L1-L2",
      "L2-L3",
      "L1-L3",
      "M1-M2",
      "M2-M3",
      "M1-M3",
      "N1-N2",
      "N2-N3",
      "N1-N3",
    ],
  },
  {
    parejas: 43,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2F",
      "1I",
      "2J",
      "1E",
      "2N",
      "1G",
      "2L",
      "1K",
      "2H",
      "1M",
      "2D",
      "1C",
      "Bye",
      "1D",
      "3A",
      "1N",
      "2C",
      "1L",
      "2G",
      "1F",
      "2I",
      "1H",
      "2M",
      "1J",
      "2K",
      "2A",
      "2E",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 28, 29, 43] },
      { nombre: "Zona B", parejas: [2, 27, 30] },
      { nombre: "Zona C", parejas: [3, 26, 31] },
      { nombre: "Zona D", parejas: [4, 25, 32] },
      { nombre: "Zona E", parejas: [5, 24, 33] },
      { nombre: "Zona F", parejas: [6, 23, 34] },
      { nombre: "Zona G", parejas: [7, 22, 35] },
      { nombre: "Zona H", parejas: [8, 21, 36] },
      { nombre: "Zona I", parejas: [9, 20, 37] },
      { nombre: "Zona J", parejas: [10, 19, 38] },
      { nombre: "Zona K", parejas: [11, 18, 39] },
      { nombre: "Zona L", parejas: [12, 17, 40] },
      { nombre: "Zona M", parejas: [13, 16, 41] },
      { nombre: "Zona N", parejas: [14, 15, 42] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
      "J1-J2",
      "J2-J3",
      "J1-J3",
      "K1-K2",
      "K2-K3",
      "K1-K3",
      "L1-L2",
      "L2-L3",
      "L1-L3",
      "M1-M2",
      "M2-M3",
      "M1-M3",
      "N1-N2",
      "N2-N3",
      "N1-N3",
    ],
  },
  {
    parejas: 44,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2F",
      "1I",
      "2J",
      "1E",
      "2N",
      "1G",
      "2L",
      "1K",
      "2H",
      "1M",
      "2D",
      "1C",
      "3B",
      "1D",
      "3A",
      "1N",
      "2C",
      "1L",
      "2G",
      "1F",
      "2I",
      "1H",
      "2M",
      "1J",
      "2K",
      "2A",
      "2E",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 28, 29, 43] },
      { nombre: "Zona B", parejas: [2, 27, 30, 44] },
      { nombre: "Zona C", parejas: [3, 26, 31] },
      { nombre: "Zona D", parejas: [4, 25, 32] },
      { nombre: "Zona E", parejas: [5, 24, 33] },
      { nombre: "Zona F", parejas: [6, 23, 34] },
      { nombre: "Zona G", parejas: [7, 22, 35] },
      { nombre: "Zona H", parejas: [8, 21, 36] },
      { nombre: "Zona I", parejas: [9, 20, 37] },
      { nombre: "Zona J", parejas: [10, 19, 38] },
      { nombre: "Zona K", parejas: [11, 18, 39] },
      { nombre: "Zona L", parejas: [12, 17, 40] },
      { nombre: "Zona M", parejas: [13, 16, 41] },
      { nombre: "Zona N", parejas: [14, 15, 42] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B4",
      "B2-B3",
      "BG1-BG2",
      "BP1-BP2",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
      "J1-J2",
      "J2-J3",
      "J1-J3",
      "K1-K2",
      "K2-K3",
      "K1-K3",
      "L1-L2",
      "L2-L3",
      "L1-L3",
      "M1-M2",
      "M2-M3",
      "M1-M3",
      "N1-N2",
      "N2-N3",
      "N1-N3",
    ],
  },
  {
    parejas: 45,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2F",
      "1I",
      "2J",
      "1E",
      "2N",
      "1G",
      "2L",
      "1K",
      "2H",
      "1M",
      "2D",
      "1C",
      "2O",
      "1D",
      "2M",
      "1N",
      "2C",
      "1L",
      "2G",
      "1F",
      "2I",
      "1H",
      "2K",
      "1J",
      "2E",
      "1O",
      "2A",
      "1B",
      "Bye",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 30, 31] },
      { nombre: "Zona B", parejas: [2, 29, 32] },
      { nombre: "Zona C", parejas: [3, 28, 33] },
      { nombre: "Zona D", parejas: [4, 27, 34] },
      { nombre: "Zona E", parejas: [5, 26, 35] },
      { nombre: "Zona F", parejas: [6, 25, 36] },
      { nombre: "Zona G", parejas: [7, 24, 37] },
      { nombre: "Zona H", parejas: [8, 23, 38] },
      { nombre: "Zona I", parejas: [9, 22, 39] },
      { nombre: "Zona J", parejas: [10, 21, 40] },
      { nombre: "Zona K", parejas: [11, 20, 41] },
      { nombre: "Zona L", parejas: [12, 19, 42] },
      { nombre: "Zona M", parejas: [13, 18, 43] },
      { nombre: "Zona N", parejas: [14, 17, 44] },
      { nombre: "Zona O", parejas: [15, 16, 45] },
    ],
    partidos: [
      "A1-A2",
      "A2-A3",
      "A1-A3",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
      "J1-J2",
      "J2-J3",
      "J1-J3",
      "K1-K2",
      "K2-K3",
      "K1-K3",
      "L1-L2",
      "L2-L3",
      "L1-L3",
      "M1-M2",
      "M2-M3",
      "M1-M3",
      "N1-N2",
      "N2-N3",
      "N1-N3",
      "O1-O2",
      "O2-O3",
      "O1-O3",
    ],
  },
  {
    parejas: 46,
    round: 16,
    llave: [
      "1A",
      "Bye",
      "2B",
      "2F",
      "1I",
      "2J",
      "1E",
      "2N",
      "1G",
      "2L",
      "1K",
      "2H",
      "1M",
      "2D",
      "1C",
      "2O",
      "1D",
      "2M",
      "1N",
      "2C",
      "1L",
      "2G",
      "1F",
      "2I",
      "1H",
      "2K",
      "1J",
      "2E",
      "1O",
      "2A",
      "1B",
      "3A",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 30, 31, 46] },
      { nombre: "Zona B", parejas: [2, 29, 32] },
      { nombre: "Zona C", parejas: [3, 28, 33] },
      { nombre: "Zona D", parejas: [4, 27, 34] },
      { nombre: "Zona E", parejas: [5, 26, 35] },
      { nombre: "Zona F", parejas: [6, 25, 36] },
      { nombre: "Zona G", parejas: [7, 24, 37] },
      { nombre: "Zona H", parejas: [8, 23, 38] },
      { nombre: "Zona I", parejas: [9, 22, 39] },
      { nombre: "Zona J", parejas: [10, 21, 40] },
      { nombre: "Zona K", parejas: [11, 20, 41] },
      { nombre: "Zona L", parejas: [12, 19, 42] },
      { nombre: "Zona M", parejas: [13, 18, 43] },
      { nombre: "Zona N", parejas: [14, 17, 44] },
      { nombre: "Zona O", parejas: [15, 16, 45] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
      "J1-J2",
      "J2-J3",
      "J1-J3",
      "K1-K2",
      "K2-K3",
      "K1-K3",
      "L1-L2",
      "L2-L3",
      "L1-L3",
      "M1-M2",
      "M2-M3",
      "M1-M3",
      "N1-N2",
      "N2-N3",
      "N1-N3",
      "O1-O2",
      "O2-O3",
      "O1-O3",
    ],
  },
  {
    parejas: 47,
    round: 16,
    llave: [
      "1A",
      "3B",
      "2B",
      "2F",
      "1I",
      "2J",
      "1E",
      "2N",
      "1G",
      "2L",
      "1K",
      "2H",
      "1M",
      "2D",
      "1C",
      "2O",
      "1D",
      "2M",
      "1N",
      "2C",
      "1L",
      "2G",
      "1F",
      "2I",
      "1H",
      "2K",
      "1J",
      "2E",
      "1O",
      "2A",
      "1B",
      "3A",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 30, 31, 46] },
      { nombre: "Zona B", parejas: [2, 29, 32, 47] },
      { nombre: "Zona C", parejas: [3, 28, 33] },
      { nombre: "Zona D", parejas: [4, 27, 34] },
      { nombre: "Zona E", parejas: [5, 26, 35] },
      { nombre: "Zona F", parejas: [6, 25, 36] },
      { nombre: "Zona G", parejas: [7, 24, 37] },
      { nombre: "Zona H", parejas: [8, 23, 38] },
      { nombre: "Zona I", parejas: [9, 22, 39] },
      { nombre: "Zona J", parejas: [10, 21, 40] },
      { nombre: "Zona K", parejas: [11, 20, 41] },
      { nombre: "Zona L", parejas: [12, 19, 42] },
      { nombre: "Zona M", parejas: [13, 18, 43] },
      { nombre: "Zona N", parejas: [14, 17, 44] },
      { nombre: "Zona O", parejas: [15, 16, 45] },
    ],
    partidos: [
      "A1-A4",
      "A2-A3",
      "AG1-AG2",
      "AP1-AP2",
      "B1-B4",
      "B2-B3",
      "BG1-BG2",
      "BP1-BP2",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
      "J1-J2",
      "J2-J3",
      "J1-J3",
      "K1-K2",
      "K2-K3",
      "K1-K3",
      "L1-L2",
      "L2-L3",
      "L1-L3",
      "M1-M2",
      "M2-M3",
      "M1-M3",
      "N1-N2",
      "N2-N3",
      "N1-N3",
      "O1-O2",
      "O2-O3",
      "O1-O3",
    ],
  },
  {
    parejas: 48,
    round: 16,
    llave: [
      "1A",
      "2B",
      "1P",
      "2O",
      "1I",
      "2J",
      "1E",
      "2F",
      "1G",
      "2H",
      "1K",
      "2L",
      "1M",
      "2N",
      "1C",
      "2D",
      "1D",
      "2C",
      "1N",
      "2M",
      "1L",
      "2K",
      "1F",
      "2E",
      "1H",
      "2G",
      "1J",
      "2I",
      "1O",
      "2P",
      "1B",
      "2A",
    ],
    grupo: [
      { nombre: "Zona A", parejas: [1, 32, 33] },
      { nombre: "Zona B", parejas: [2, 31, 34] },
      { nombre: "Zona C", parejas: [3, 30, 35] },
      { nombre: "Zona D", parejas: [4, 29, 36] },
      { nombre: "Zona E", parejas: [5, 28, 37] },
      { nombre: "Zona F", parejas: [6, 27, 38] },
      { nombre: "Zona G", parejas: [7, 26, 39] },
      { nombre: "Zona H", parejas: [8, 25, 40] },
      { nombre: "Zona I", parejas: [9, 24, 41] },
      { nombre: "Zona J", parejas: [10, 23, 42] },
      { nombre: "Zona K", parejas: [11, 22, 43] },
      { nombre: "Zona L", parejas: [12, 21, 44] },
      { nombre: "Zona M", parejas: [13, 20, 45] },
      { nombre: "Zona N", parejas: [14, 19, 46] },
      { nombre: "Zona O", parejas: [15, 18, 47] },
      { nombre: "Zona P", parejas: [16, 17, 48] },
    ],
    partidos: [
      "A1-A2",
      "A2-A3",
      "A1-A3",
      "B1-B2",
      "B2-B3",
      "B1-B3",
      "C1-C2",
      "C2-C3",
      "C1-C3",
      "D1-D2",
      "D2-D3",
      "D1-D3",
      "E1-E2",
      "E2-E3",
      "E1-E3",
      "F1-F2",
      "F2-F3",
      "F1-F3",
      "G1-G2",
      "G2-G3",
      "G1-G3",
      "H1-H2",
      "H2-H3",
      "H1-H3",
      "I1-I2",
      "I2-I3",
      "I1-I3",
      "J1-J2",
      "J2-J3",
      "J1-J3",
      "K1-K2",
      "K2-K3",
      "K1-K3",
      "L1-L2",
      "L2-L3",
      "L1-L3",
      "M1-M2",
      "M2-M3",
      "M1-M3",
      "N1-N2",
      "N2-N3",
      "N1-N3",
      "O1-O2",
      "O2-O3",
      "O1-O3",
      "P1-P2",
      "P2-P3",
      "P1-P3",
    ],
  },
];

/**
 * Rondas posteriores a la primera, por tamano de cuadro. Son fijas: una vez
 * resuelta la primera ronda ya no hay Byes, asi que el resto del cuadro no
 * depende de la cantidad de parejas.
 */
export const RONDAS_POSTERIORES: Record<LlaveRound, readonly string[]> = {
  16: ["OF1", "OF2", "OF3", "OF4", "OF5", "OF6", "OF7", "OF8", "CF1", "CF2", "CF3", "CF4", "SF1", "SF2", "F1"],
  8: ["CF1", "CF2", "CF3", "CF4", "SF1", "SF2", "F1"],
  4: ["SF1", "SF2", "F1"],
};

/** Devuelve la entrada de la tabla para esa cantidad de parejas, o null si esta fuera de 7-48. */
export function getLlavePorParejas(cantidad: number): LlaveEntry | null {
  return LLAVE_TABLA.find((item) => item.parejas === cantidad) ?? null;
}

export const LLAVE_MIN_PAREJAS = LLAVE_TABLA[0].parejas;
export const LLAVE_MAX_PAREJAS = LLAVE_TABLA[LLAVE_TABLA.length - 1].parejas;
