-- AlterTable
ALTER TABLE `Notification` MODIFY `type` ENUM('MATCH_REMINDER', 'MATCH_1H_REMINDER', 'MATCH_CHANGED', 'TOURNAMENT_START', 'TOURNAMENT_UPDATE', 'NEW_TOURNAMENT', 'RESULT_UPDATE', 'SYSTEM') NOT NULL;
-- AlterTable
ALTER TABLE `Torneo` MODIFY `status` ENUM('DRAFT', 'PUBLISHED', 'CLOSED_REGISTRATION', 'IN_PROGRESS', 'FINISHED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT';
-- AlterTable
ALTER TABLE `User` ADD COLUMN `notificationPreferences` JSON NULL;
