-- AlterTable
ALTER TABLE `Torneo`
    ADD COLUMN `sexo` ENUM('MASCULINO', 'FEMENINO', 'MIXTO') NOT NULL DEFAULT 'MIXTO',
    ADD COLUMN `categoriaRegla` ENUM('LIBRE', 'MAYOR_IGUAL', 'MENOR_IGUAL', 'IGUAL', 'SUMA') NOT NULL DEFAULT 'LIBRE',
    ADD COLUMN `categoriaN` INTEGER NULL;
