-- AlterTable
ALTER TABLE `Torneo` ADD COLUMN `formato` ENUM('ZONAS', 'ELIMINACION_DIRECTA') NOT NULL DEFAULT 'ZONAS',
    ADD COLUMN `siembra` ENUM('RANKING', 'INSCRIPCION') NOT NULL DEFAULT 'INSCRIPCION';
